### ISSUE TITLE
Help Panel

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#155]
**Summary**
A panel that provides information about what the user is currently seeing and how to use the tool.

**Tasks**
- [x] [functional specification](https://github.com/Hyperobjekt/seda-map/wiki/Functional-Specification#help-panel)
- [x] wireframe (May 26)
- [x] sample of "what am i seeing" panel content for avg. test scores vs. socioeconomic status (June 1)
- [x] sample of "how do i use this" panel content (June 1)
- [x] prototype (June 17)
- [ ] final content delivery (July 1)
- [ ] beta (July 8)
- [ ] QA (August 1)

**Comment by Lane** [comment]
[Specification for "Help Panel"](https://github.com/Hyperobjekt/seda-map/wiki/Functional-Specification#help-panel)

@james-minton who is writing the content / robotext for the "What am I seeing?" and "How do I use this?" parts of the panel.  Could we get a sample of this content?

**Comment by james-minton** [comment]
@Lane probably best way forward is for me to make an outline / provisional copy we can all work from and then let SEDA adapt. If you’d like to set a target date for this please feel free :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lane** [comment]
@james-minton added a checklist to the original issue.  i have june 1 set as a deliverable date for sample content, let me know if that needs to be changed.
