### ISSUE TITLE
Location Comparison Dialog

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#354]
Remove location comparison from the location panel and open it in its own dialog window.

- [ ] should allow subgroup selection
- [ ] should allow adding a location via search
- [ ] should allow loading similar locations (see #375)
- [ ] should allow exporting locations in the table to CSV (see #376)
- [ ] should display locations in location comparison table (see #374)
- [ ] should have a mobile-friendly view

![image](https://user-images.githubusercontent.com/21034/102816518-02b31680-4383-11eb-98a8-800913a9c3a8.png)

**Comment by Lane** [comment]
Latest revision including subgroup / gap selection:

![image](https://user-images.githubusercontent.com/21034/87810609-7a03dd80-c81a-11ea-8aa9-91250d48c72a.png)
