### ISSUE TITLE
4.1 Discovery Design Updates

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/seda-map#602]
## Objective
Implement further design changes to the 4.1 NAM discovery article

## Tasks
- [ ] Widen text column slightly 
- [ ] Set slightly narrower max-width on the visualization 
- [ ] Implement blue background box for search/selection panel
- [ ] Move legend to beneath the chart
- [ ] Increase size of axis labels 

## Reference
[Spec](https://www.figma.com/file/15hzSKjYOAqFqC7hzQEUej/SEDA---Discoveries-%26-4.0-updates---DRAFT?node-id=408%3A2)
