### ISSUE TITLE
Style Compare/DownloadReport Buttons

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/seda-map#603]
## Objective
Apply design outlined in mockups to two buttons within the SEDA map explorer location panel: "Compare Districts" and "Download Report"

Note: The SEDA team is still finalizing the background color, this might be subject to change. 

## Reference
Mockups can be found [here](https://www.figma.com/file/qF5XAaWJwif5iV8a4a2h8B/SEDA-v1.1.0?node-id=1647%3A628)

## Screenshots
(Note: only buttons should be updated from designs) 

Current View
![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/dccb87f6-e697-4cd6-9974-93c558ae6d25)

Target View
![Screen Shot 2021-06-28 at 5.27.55 PM.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/898c382b-6f74-4f0c-bc27-8f72df4b06bd)

**Comment by Lane** [comment]
Additional request from @james-minton:

>There is a request to restyle the compare locations/download report buttons in the location panel per this mockup (just adopting the button styles at bottom right).
To add to that: for consistency, can these buttons in the "compare locations" dialog also be styled according to this mockup (meaning just change the font color to #0071DB)? 1st image is what's on the site now, and 2nd is what's desired.

![image](https://user-images.githubusercontent.com/21034/124803500-0b79cd00-df0e-11eb-9020-97a61b3b6db5.png)

## Tasks

- [ ] update "Compare Locations" button in location panel to include outlined button, icon, and primary text color (`theme.palette.primary.main`)
- [ ] update "Download Report" button in location panel to include outlined button, icon, and primary text color (`theme.palette.primary.main`)
- [ ] update "Load Similar" and "Save as CSV" to use primary text color (`theme.palette.primary.main`)
