### ISSUE TITLE
underlay doot layer should have dynamic sizing

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#610]
## Current Behaviour

the underlay layer of grey dots are not sized to match the size of the foreground layer.  this is for performance reasons, as dynamic sizing cannot be applied to a large dot collection with eCharts.

## Desired Behaviour

the underlay dot sizing should match the foreground layer.

## Tasks

- [ ] spec and estimate two potential approaches (@Lane)
  - [ ] (low effort) limit underlay layer to 10,000 by size, add hinting that filters should be adjusted to focus on an area.
  - [ ] (high effort) limit underlay to 10,000, but filter dots based on proximity to other dots so that overlapping dots would be removed.
- [ ] receive approval from client on which approach is preferred (@ekmason)
- [ ] implement approved specification (TBD)

**Comment by Lane** [comment]
@ekmason i worked on this today and with some experimenting i was able to add sizing to the underlay dots by reducing the dataset based on proximity.  i have pushed this update to the [development version of the explorer](https://dev.edopportunity.org/explorer/#/chart/limit,1000/schools/avg/frl/all/3.15/37.39/-96.78/)

this does lead to a drop in performance when rendering the underlay (mostly on the schools dataset), though this is unavoidable.  if the performance impact is too much, i can further simplify the dataset for the underlay.

the good news is that if this solution is good with them, we don't need an additional story!
