### ISSUE TITLE
Spec + Estimate Additive Filters

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#611]
## Current Behaviour

all available filters are shown when you open the filter panel.  this can be difficult to determine which filters are currently active.

## Desired Behaviour

the filter panel should only show filters that are currently active, and allow users to add / remove them as needed.

## Tasks

- [ ] write specification for this feature (@Lane)
- [ ] create task breakdown and estimate (@Lane)
- [ ] received client approval to implement (@ekmason)
- [ ] implement according to spec (TBD)

**Comment by Lane** [comment]
## Specification

- "reset filters" button moved to panel header
- checkbox filters are replaced with button groups, so all filter types are present upon opening the panel
  - "Bureau of Indian Education" option is shortened to "BIE" with a tooltip to conserve space. 
- metric sliders are removed, and updated with a menu button that reads "add metric filter"
  - on button press: a menu opens with available metrics for filtering
  - on menu item selection: a slider appears corresponding to the selected metric
  - metric sliders function as before, with the addition of a "remove filter" button
    - on "remove filter" click: the slider for the corresponding metric is removed and the filter is no longer applied

## Prototype

https://user-images.githubusercontent.com/21034/125860135-bde5bd2c-5c8f-49c6-87be-bf9378a584f7.mov

## Estimate

a prototype of this functionality is in the `spec/additive-filters` branch.  remaining tasks include:

- [ ] connect "reset filters" button to application logic, set to disabled state when no filters are active
- [ ] set disabled state on button groups when in a region where they cannot be applied (e.g. "school type" in "counties" view)
- [ ] connect removing metric filters to application logic
- [ ] apply any design revisions
- [ ] refactor styles to remove inline styles for prototyping purposes

estimated at 3 story points.

**Comment by Lane** [comment]
WIP in the `spec/additive-filters` branch: https://github.com/Hyperobjekt/seda-map/tree/spec/additive-filters
